export { findByEmail } from "./user.findByEmail";
export { findByPseudo } from "./user.findByPseudo";
export { fetchFriends } from "./user.fetchFriends";
export { removeFriendById } from "./user.removeFriendById";
export { findById, findByIdWithPopulate } from "./user.findById";
export { save } from "./user.save";
export { updateById } from "./user.updateById";
export { addFriendById } from "./user.addFriendById";
export { searchByPseudo } from "./user.searchByPseudo";
export { fetchDecks } from "./user.fetchDecks";
